# Generated by Django 3.2.7 on 2021-09-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSVColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.CharField(max_length=3)),
                ('h_value', models.PositiveIntegerField()),
                ('s_value', models.PositiveIntegerField()),
                ('v_value', models.PositiveIntegerField()),
                ('operation', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'HSV colors',
            },
        ),
    ]
