# Generated by Django 3.2.7 on 2021-09-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hsvcolor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.CharField(max_length=3)),
                ('operation', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('color_a', models.IntegerField()),
                ('color_b', models.IntegerField()),
                ('color_c', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Color Operations',
                'ordering': ('operation',),
            },
        ),
    ]
